---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - demo.operator.anishbista.xyz
  resources:
  - scalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.operator.anishbista.xyz
  resources:
  - scalers/finalizers
  verbs:
  - update
- apiGroups:
  - demo.operator.anishbista.xyz
  resources:
  - scalers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - create
  - update
  - list
  - watch 

